@startuml
autonumber
skinparam wrapWidth 150
skinparam ParticipantPadding 10

actor "Reclutador" as Rec
participant "Interfaz de\nusuario" as IU
participant "Controlador\nde candidatos" as Ctrl
database "Base\nde Datos" as DB
participant "Servicio de\ncorreo\nexterno" as API

Rec -> IU: Ingresa calificación, comentarios\ny nuevo estado
IU -> Ctrl: Actualizar Evaluación\n(Id Postulación, calificación, Estado)
Ctrl -> DB: Actualizar Estado y calificaciones
DB --> Ctrl: Confirmación de actualización
Ctrl -> API: Enviar notificación
API --> Ctrl: Confirmación de envío
Ctrl --> IU: Retorna Éxito del proceso
IU --> Rec: Muestra mensaje de Evaluación\nguardada correctamente
@enduml